### ISSUE TITLE
How to build/run? [Question - Not a bug]

### ISSUE THREAD

**Issue by DesktopECHO** [FilBot3/com.vmware.HorizonClient#19]
Hi There, thanks for putting this together.  

I'm fairly new when it comes to working with Flatpaks; can you offer any guidance/links on how to instal this it would be greatly appreciated.  Normally when I see a Flatpak it's a single installable file.  

Thanks!
D.

**Comment by HugLifeTiZ** [comment]
Check out the git repo, and then from inside the directory:

```
flatpak-builder --user --install --force-clean build com.vmware.HorizonClient.yaml
```

It will probably complain about org.gnome.Sdk version 41 missing. You can install it with `flatpak install org.gnome.Sdk//41`.

**Comment by DesktopECHO** [comment]
Thank you!  These instructions worked perfectly. 
Unfortunately when I try to connect with PCoIP, all I get is a black screen with a (working) Windows mouse pointer.  This machine's CPU doesn't support Blast so I was hoping to run this alongside the 7.x client which did have a working Blast protocol.  Will dig around the logs later.  
I'll close this issue and open a new one if I have more info on the PCoIP problems.  @FilBot3 you should put Hug's Flatpak install instruction in README.md or I can PR it if you like?
